### ISSUE TITLE
Refresh token in implicit flow

### ISSUE THREAD

**Issue by micgwork** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1019]
Hi,

We utilise implicit flow against our OpenID-Connect-Java-Spring-Server OIDC back-end server.  Is it possible to attain a refresh token using implicit flow?  If so, could you please give an example POST request (to /token endpoint)?

How do we refresh our access_token?

Thanks.

**Comment by jricher** [comment]
The short answer is that you can't. The implicit flow does not use the token endpoint and does not offer refresh tokens. Since implicit flows are supposed to only be used for in-browser JavaScript clients, there's not much point in keeping a refresh token around. If you're using the implicit flow for a different kind of client, you're likely not using OAuth in the best way.
