### ISSUE TITLE
Token Introspection doesn't returns scopes list

### ISSUE THREAD

**Issue by ericktedeschi** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1028]
Hi everyone,
I'm testing the mitreid-connect (commit 078159235792b86efc8a3e24d50d64993dcecd77).

Well, I created a Client able to use client_credentials as grant type and associates a scope like "role:capability". The AS returns a JWT access_token and the scope granted, this is the expected.
But when I try to introspect the token from the Resource Server (with it's own credentials), the scope list comes empty:

Check below the flow I made:
Client requesting token to communicate with RS (scope role:name):
`curl -i -u "client1:client_secret" -d "grant_type=client_credentials&scope=role:name" -H "Content-Type: application/x-www-form-urlencoded" http://localhost:8080/openid-connect-server-webapp/token`

Response

`{"access_token":"eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJjbGllbnQxIiwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjgwODBcL29wZW5pZC1jb25uZWN0LXNlcnZlci13ZWJhcHBcLyIsImV4cCI6MTQ1NjMyNDA1MiwiaWF0IjoxNDU2MzIwNDUyLCJqdGkiOiJlZTM1NjEyNC1hNWJmLTRkOTMtYTE3Zi00NTFiNmYyNDNjYjMifQ.Wiz9RVZyNyzg0F3JuVEQaE0VlAPDFaU__M7oaX4C-53VcCF2pAKhLocadV8OagvRTSMrVR-SkbDNWvx5VZ-jJIyDKe03aZ69rkCcIMWiSlo7Y6nYLnWOrfPyLGVZM2lM1rSIVC9FFdOZRP1Mn8-3mJ_jU0x-7Tvnl0u0IDlSGAKjCjMYBUcSqW0SWFKOWX8Q1oQcy1YAfM3gohapy7evOIrVO8YVj73AZ5-Gdpm7VJhySZDxQ8g9Xpge2GWm732zOeY9Tf1SLiy2P8n7nsL6QWdetMWwmg7k4Sqtl0J5hwkLiFSDWEZb1qd_U2VaGPazjpIUjzbSWGByJbeje1BPjw","token_type":"Bearer","expires_in":3599,"scope":"role:name"}`

Resource Server (user rs1) making Introspection:

`curl -i -u "rs1:resourceserversecret" -d "token=eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJjbGllbnQxIiwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjgwODBcL29wZW5pZC1jb25uZWN0LXNlcnZlci13ZWJhcHBcLyIsImV4cCI6MTQ1NjMyNDA1MiwiaWF0IjoxNDU2MzIwNDUyLCJqdGkiOiJlZTM1NjEyNC1hNWJmLTRkOTMtYTE3Zi00NTFiNmYyNDNjYjMifQ.Wiz9RVZyNyzg0F3JuVEQaE0VlAPDFaU__M7oaX4C-53VcCF2pAKhLocadV8OagvRTSMrVR-SkbDNWvx5VZ-jJIyDKe03aZ69rkCcIMWiSlo7Y6nYLnWOrfPyLGVZM2lM1rSIVC9FFdOZRP1Mn8-3mJ_jU0x-7Tvnl0u0IDlSGAKjCjMYBUcSqW0SWFKOWX8Q1oQcy1YAfM3gohapy7evOIrVO8YVj73AZ5-Gdpm7VJhySZDxQ8g9Xpge2GWm732zOeY9Tf1SLiy2P8n7nsL6QWdetMWwmg7k4Sqtl0J5hwkLiFSDWEZb1qd_U2VaGPazjpIUjzbSWGByJbeje1BPjw" -H "Content-Type: application/x-www-form-urlencoded" http://localhost:8080/openid-connect-server-webapp/introspect`

Response:

`{"active":true,"scope":"","expires_at":"2016-02-24T11:27:32-0300","exp":1456324052,"sub":"client1","user_id":"client1","client_id":"client1","token_type":"Bearer"}`

Check that the scope comes empty. All other information is ok.
Thank you in advance

**Comment by jricher** [comment]
The resource server needs to have listed any scopes that it wants to introspect. Add those to the resource server's registration and they should come back in the list. We do this to limit potential information leaking about tokens that could be used at multiple RS's.

**Comment by mingdatacom** [comment]
Hi All
The example above about is for a resource server, I want to know if it is possible to use the "IntrospectingTokenService" for the client?
I've added the following to the "simple-web-app":

	
	<oauth:resource-server id="resourceServerFilter" token-services-ref="introspectingService" />
	
	<bean id="introspectingService" class="org.mitre.oauth2.introspectingfilter.IntrospectingTokenService">
	    <property name="introspectionConfigurationService" ref="staticIntrospectionConfigurationService">
	    </property>
	</bean>

	<bean class="org.mitre.oauth2.introspectingfilter.service.impl.StaticIntrospectionConfigurationService" id="staticIntrospectionConfigurationService">
	   <property name="introspectionUrl" value="http://localhost:8080/openid-connect-server-webapp/introspect" />
	   <property name="clientConfiguration">
	     <bean class="org.mitre.oauth2.model.RegisteredClient">
	       <property name="clientId" value="XXX"/>
	       <property name="clientSecret" value="XXX"/>
	     </bean>
	   </property>
	</bean>

I got the example from: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Token-Introspecting-Client-Config
How do I use the "introspectingService" inside "simple-web-app" to get the list of enabled scopes?
The authorization request comes from the client("simple-web-app") to the auth-server(MITREid-Connect) to the user, so is it possible for the client to know which scopes the user has enabled for the client? 

Thanks In Advance

**Comment by jricher** [comment]
The client shouldn't ever need to introspect a token, since the client just uses the token. The server will report back the scopes associated with the token as part of the original token response, but ultimately the client will just use the token with the resources and see if it works. That said, there's nothing preventing you from using token introspection with a client, it just doesn't make sense and so we don't really have the service set up to do that.

**Comment by merric** [comment]
@jricher, 

I also am struggling to see the point of the introspection endpoint. The scopes that return have nothing to do with the actual access token pass. Instead its my own (the client making the call) scopes that are returned, which I feel I already know about. If I wanted to use my own scopes I'd just make a client creds call if I was enabled to or would get back the scopes on token request. 


What we need is to know what kind of permissions were given to the access token on the client/resource owner's behalf. Without this we don't know if a less trusted app is passing its access tokens to what should be a more secure app. Our understanding is that this is where scopes come in.

**Our example scenario is this:** 

An external app registers with our IDP and is given basic scopes. Its a mobile app so its given password grant type. It creates an access token. Later this access token is passed to a trusted server side application. This client has many more security scopes. We want to know two things:

1. Is this a valid user from the IDP. 
2. Does the access token have the scopes we use to mean it can access this more secure application. 

The first concern is taken care of by introspection. We get whether the token is active or not. 

Currently the second concern isn't solvable under the current implementation. This less secure app shouldn't be able to call this secure server. Unfortunately, we can't tell because only the secure sever's scopes are returned. More over, when  using AuthCode grant type we have no way of knowing what a user has authorized unless we try every endpoint. We incur performance penalties when we must call the AS and fail instead of knowing to fall to an exception or other in the absence of needed scopes.

**Comment by jricher** [comment]
This is why I said it didn't make sense for the client to call the introspection endpoint, it's made for protected resources to be able to determine what a token is good for.

If you're encoding the access rights of the token into its scopes, then that's what you'll get returned from the introspection endpoint. You'll get the subset of scopes that your protected resource is registered for, by default, but they are the scopes associated with the token. If those scopes come back then those are the scopes associated with the token. If the token didn't have those scopes, the response wouldn't have the scopes either. 

From your description, the client application wasn't given the server-side component's scopes, and so when you introspect it you don't get those scopes. That makes perfect sense. You wouldn't want that token to suddenly grow more powerful.

**Comment by merric** [comment]
I really appreciate your quick reply. You've been amazing in all the assistance you've been. 

To your response, the opposite seems to be occurring. The access token granted to the mobile app is weak. But when the server client calls introspect all the powerful scopes are returned that the client owns. In fact all of the client's scopes are returned whether the access token had them or not. 

We have this set up. 

Client 1 (non-secure mobile app): 
     Client_Scopes:
          A, B, and C
     Grant Types:
         Password
Client 2 (Secure backend client server):
     Client_Scopes:
          A, B, C, and D
     Grant Types:
          At least client creds


Client 1 makes a request and is returned immediately A, B, and C scopes as desired. He then makes a request to client 2 passing the access token. 

Client 2 wants to know if this access token can access this service so wants to check if the token is valid and has required scope D. It makes an /introspect call with its clientId and clientSecret in the header and the passed Access Token from client 1 as a query parameter. 

The endpoint returns the access token is valid, expires in X secs, came from client 1, and what we thought would be the scopes given to the access token. 

Unfortunately it returns A, B, C, and D. This fools client 2 into thinking the requester is authorized when its not. 


Are we making bad assumptions or configuration for this use case?

**Comment by jricher** [comment]
What you're describing should be impossible thanks to this line:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/oauth2/service/impl/DefaultIntrospectionResultAssembler.java#L72
