### ISSUE TITLE
How to validate token to see if expired

### ISSUE THREAD

**Issue by mpeddagolla** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1087]
Hi,

I see that thee is /oauth/check_token but how I do I access it? Or is there a way I can validate a access_token to see if it expired or invalid?

Thank you
Mallikarju

**Comment by jricher** [comment]
We don't expose the spring security OAuth library's "check_token" endpoint. We do have our own implementation of Token Introspection available at /introspect, though, and it's compliant with RFC7662. You need to have your protected resource registered with an ID and secret so that it can authenticate the call to the introspection endpoint.
