### ISSUE TITLE
APIs responses with 401 unauthorized

### ISSUE THREAD

**Issue by ondrejvelisek** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1105]
Hi,

When javascript manager client app calls `api/*` it responses with 401. However user is fully authenticated (via pre-authentication with Apache) and has proper roles. 

Request: `GET /fed/oidc/api/scopes?_=1469472629805 HTTP/1.1`
Response:
```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Bearer realm="openidconnect", error="unauthorized", error_description="Full authentication is required to access this resource"

{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}
```

Cheers,

Ondrej

**Comment by jricher** [comment]
You've almost certainly got an error in your pre-authentication configuration. Is it covering the /api calls? Are you using session cookies once the pre-authentication occurs?

**Comment by ondrejvelisek** [comment]
I was debugging it all day and did not solve anything. I'm authenticating user by my `AbstractPreAuthenticatedProcessingFilter` which returns always static string (now for this debug). My user-context looks like:

```
	<security:http auto-config="false" use-expressions="true" entry-point-ref="http403EntryPoint" >
		<security:intercept-url pattern="/**" access="hasRole('ROLE_USER')" />
		<security:custom-filter ref="perunAuthenticationFilter" position="PRE_AUTH_FILTER" />
	</security:http>

	<bean id="perunAuthenticationFilter"
		  class="cz.metacentrum.perun.oidc.overlay.PerunAuthenticationFilter">
		<property name="authenticationManager" ref="authenticationManager" />
		<property name="authenticationDetailsSource" ref="authenticationDetailsSource" />
	</bean>

	<security:authentication-manager alias="authenticationManager">
		<security:authentication-provider ref="preauthAuthProvider" />
	</security:authentication-manager>

	<bean id="authenticationDetailsSource" class="cz.metacentrum.perun.oidc.overlay.PerunAuthenticationDetailSource" />

	<bean id="preauthAuthProvider"
		  class="org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationProvider">
		<property name="preAuthenticatedUserDetailsService" ref="userDetailsService"/>
	</bean>

	<bean id="userDetailsService" class="org.springframework.security.web.authentication.preauth.PreAuthenticatedGrantedAuthoritiesUserDetailsService"/>

	<bean id="defaultUserInfoRepository" class="cz.metacentrum.perun.oidc.overlay.PerunUserInfoRepository" primary="true"/>

```

However in logs I still have:
```
DEBUG: org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Looking up handler method for path /api/scopes
DEBUG: org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Returning handler method [public java.lang.String org.mitre.oauth2.web.ScopeAPI.getAll(org.springframework.ui.ModelMap,javax.servlet.http.HttpServletRequest)]
DEBUG: org.springframework.web.servlet.DispatcherServlet - Last-Modified value for [/perun-oidc-server/api/scopes] is: -1
DEBUG: org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor - Secure object: ReflectiveMethodInvocation: public java.lang.String org.mitre.oauth2.web.ScopeAPI.getAll(org.springframework.ui.ModelMap,javax.servlet.http.HttpServletRequest); target is of class [org.mitre.oauth2.web.ScopeAPI]; Attributes: [[authorize: '#oauth2.throwOnError(hasRole('ROLE_USER'))', filter: 'null', filterTarget: 'null']]
DEBUG: org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor - Previously Authenticated: org.springframework.security.authentication.AnonymousAuthenticationToken@9055e4a6: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null; Granted Authorities: ROLE_ANONYMOUS
...
DEBUG: org.springframework.security.web.access.ExceptionTranslationFilter - Access is denied (user is anonymous); redirecting to authentication entry point
org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:83)
	...
```
However I see my (static) username in topbar and admin menu. So I'm authenticated. But API does not know my identity. 
Weird thing is that it works well in embedded tomcat7 maven plugin. But in "real" system tomcat it returns 401. 

I will appreciate any help.

**Comment by ondrejvelisek** [comment]
According to logs it did not even try to authenticate with my filter on position PRE_AUTH_FILTER:
```
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/scopes'; against '/api/**'
DEBUG: org.springframework.security.web.FilterChainProxy - /api/scopes?_=1469699515766 at position 1 of 9 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
DEBUG: org.springframework.security.web.context.HttpSessionSecurityContextRepository - No HttpSession currently exists
DEBUG: org.springframework.security.web.context.HttpSessionSecurityContextRepository - No SecurityContext was available from the HttpSession: null. A new one will be created.
DEBUG: org.springframework.security.web.FilterChainProxy - /api/scopes?_=1469699515766 at position 2 of 9 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
DEBUG: org.springframework.security.web.FilterChainProxy - /api/scopes?_=1469699515766 at position 3 of 9 in additional filter chain; firing Filter: 'OAuth2AuthenticationProcessingFilter'
DEBUG: org.springframework.security.oauth2.provider.authentication.BearerTokenExtractor - Token not found in headers. Trying request parameters.
DEBUG: org.springframework.security.oauth2.provider.authentication.BearerTokenExtractor - Token not found in request parameters.  Not an OAuth2 request.
DEBUG: org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter - No token in request, will continue chain.
DEBUG: org.springframework.security.web.FilterChainProxy - /api/scopes?_=1469699515766 at position 4 of 9 in additional filter chain; firing Filter: 'RequestCacheAwareFilter'
DEBUG: org.springframework.security.web.FilterChainProxy - /api/scopes?_=1469699515766 at position 5 of 9 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
DEBUG: org.springframework.security.web.FilterChainProxy - /api/scopes?_=1469699515766 at position 6 of 9 in additional filter chain; firing Filter: 'AnonymousAuthenticationFilter'
DEBUG: org.springframework.security.web.FilterChainProxy - /api/scopes?_=1469699515766 at position 7 of 9 in additional filter chain; firing Filter: 'SessionManagementFilter'
DEBUG: org.springframework.security.web.session.SessionManagementFilter - Requested session ID 3AD0C831F3A0207A65A45368C12441F8 is invalid.
DEBUG: org.springframework.security.web.FilterChainProxy - /api/scopes?_=1469699515766 at position 8 of 9 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
DEBUG: org.springframework.security.web.FilterChainProxy - /api/scopes?_=1469699515766 at position 9 of 9 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
```

**Comment by ondrejvelisek** [comment]
OK. Finally I fixed it. However I do not know what is wrong. Anyway when I deploy my webapp directly to tomcat root (without contextPath) e.g. `ajp://104.0.0.4:8809/` and set up apache proxy it works fine. But if I deploy it to e.g. `ajp://104.0.0.4:8809/perun-oidc-server` and set up apache proxy it returns 401.

**Comment by jricher** [comment]
From your logs it looks like your preauth filter isn't firing on the API for some reason that I can't see from the configuration. Don't know what's causing it. This server code has been run on root and non-root contexts with different AJP configurations without seeing this issue before. Not sure what to tell you, but I'm glad it's working.

**Comment by magaram2** [comment]
I am running into a similar situation where my rest service returns a 401 even though it is fully authenticated. I was able to test GET http://localhost:8080/openid-connect-server-webapp/clients successfully from postman using the same access token. 

However when I test my rest service I get a 401

{
  "error": "unauthorized",
  "error_description": "Full authentication is required to access this resource"
}

//Rest service snippet
@RestController
@Component
@RequestMapping(value = "/api/ContextModel")
@PreAuthorize("hasRole('ROLE_USER')")
public class MySampleService {
         ...	
	@RequestMapping(value = "/getAll", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<String> getAll(Authentication auth) {
               ...
	}
	
////Spring wiring/////
	<security:global-method-security pre-post-annotations="enabled" proxy-target-class="true" authentication-manager-ref="authenticationManager"/>	

 	<security:http pattern="/api/**" use-expressions="true" entry-point-ref="oauthAuthenticationEntryPoint" create-session="never">
		<security:custom-filter ref="openIdConnectAuthenticationFilter" before="PRE_AUTH_FILTER" />
	</security:http>

	<security:authentication-manager alias="authenticationManager">
		<security:authentication-provider ref="openIdConnectAuthenticationProvider" />
	</security:authentication-manager>

	<bean id="openIdConnectAuthenticationProvider" class="org.mitre.openid.connect.client.OIDCAuthenticationProvider">
		<property name="authoritiesMapper">
			<bean class="org.mitre.openid.connect.client.NamedAdminAuthoritiesMapper">
				<property name="admins" ref="namedAdmins" />
			</bean>
		</property>
	</bean>

**Comment by szabe74** [comment]
Hi,
I have faced same issue in my job. My task is to upgrade the mitreID from 1.2.3 to 1.3.1. Everything works fine except the mitreId Admin page 401 Error issue.
I have started to investigate what is behind so i found this topic. I am working on it but I would appreciate some help from the experts.

Some info about the issue:

The error message on admin page after I click on Manage Client button:

![image](https://user-images.githubusercontent.com/29603312/27387012-cb2401ba-5697-11e7-8178-83232f89cf33.png)

I am trying it in a local enviroment (localhost), I haven't deployed it to productive enviroment because I have to solve it locally. The workaround of ondrejvelisek is not good for me, I need a solution. In my server.xml the context path is: `path="/iii-services/0.1/oidc"` 

Here is the debug level log from the mitreId server:

`org.springframework.security.web.context.SecurityContextPersistenceFilter - SecurityContextHolder now cleared, as request processing completed
org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/extendedClients'; against '/token'
org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/extendedClients'; against '/jwk**'
org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/extendedClients'; against '/.well-known/**'
org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/extendedClients'; against '/resources/**'
org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/extendedClients'; against '/register/**'
org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/extendedClients'; against '/resource/**'
org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/extendedClients'; against '/userinfo**'
org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/extendedClients'; against '/api/stats/summary**'
org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/api/extendedClients'; against '/api/**'
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 at position 1 of 10 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
org.springframework.security.web.context.HttpSessionSecurityContextRepository - Obtained a valid SecurityContext from SPRING_SECURITY_CONTEXT: 'org.springframework.security.core.context.SecurityContextImpl@9a5fec5: Authentication: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken@9a5fec5: Principal: com.company.xxx.yyy.iii.service.authentication.EnhancedUser@c5254986: Username: ZZZZXXXX; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@1c07a: RemoteIpAddress: 127.0.0.1; SessionId: 70E65774887F05FCCF87A9858F1B5767; Granted Authorities: ROLE_ADMIN, ROLE_USER'
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 at position 2 of 10 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 at position 3 of 10 in additional filter chain; firing Filter: 'HeaderWriterFilter'
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 at position 4 of 10 in additional filter chain; firing Filter: 'OAuth2AuthenticationProcessingFilter'
org.springframework.security.oauth2.provider.authentication.BearerTokenExtractor - Token not found in headers. Trying request parameters.
org.springframework.security.oauth2.provider.authentication.BearerTokenExtractor - Token not found in request parameters.  Not an OAuth2 request.
org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter - Clearing security context.
org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter - No token in request, will continue chain.
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 at position 5 of 10 in additional filter chain; firing Filter: 'RequestCacheAwareFilter'
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 at position 6 of 10 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 at position 7 of 10 in additional filter chain; firing Filter: 'AnonymousAuthenticationFilter'
org.springframework.security.web.authentication.AnonymousAuthenticationFilter - Populated SecurityContextHolder with anonymous token: 'org.springframework.security.authentication.AnonymousAuthenticationToken@6faba4dc: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@fffed504: RemoteIpAddress: 127.0.0.1; SessionId: 1ED18C52FA92B0CF129042B3CF4EB535; Granted Authorities: ROLE_ANONYMOUS'
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 at position 8 of 10 in additional filter chain; firing Filter: 'SessionManagementFilter'
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 at position 9 of 10 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 at position 10 of 10 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
org.springframework.security.web.access.intercept.FilterSecurityInterceptor - Public object - authentication not attempted
org.springframework.security.web.FilterChainProxy - /api/extendedClients?_=1498046578889 reached end of additional filter chain; proceeding with original chain`


My application-context.xml is same as in the github master but it contains additional resource imports.
The related entry is the same:

` 	<security:http pattern="/#{T(org.mitre.openid.connect.web.RootController).API_URL}/**" use-expressions="true" entry-point-ref="oauthAuthenticationEntryPoint" create-session="never">
		<security:custom-filter ref="resourceServerFilter" before="PRE_AUTH_FILTER" />
		<security:expression-handler ref="oauthWebExpressionHandler" />
		<security:csrf disabled="true"/>
	</security:http>
`

Thank you in advance

**Comment by szabe74** [comment]
Finally I have realized that I screwed the merge and the following important tag was missing from the application-context.xml:

**stateless="false"** was missing from here:
_<oauth:resource-server id="resourceServerFilter" token-services-ref="defaultOAuth2ProviderTokenService" stateless="false"/>_

now it works..

**Comment by jricher** [comment]
This, among other reasons, is why we don't recommend overriding the application-context.xml file.
