### ISSUE TITLE
OAuth flow redirects dropping HTTPS

### ISSUE THREAD

**Issue by jtaylor10** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1136]
I'm guessing this is a dumb configuration problem on my end and someone can help...

I have a cluster of MitreId servers deployed behind a load balancer. The load balancer is where HTTPS gets terminated and it uses HTTP to talk with each mitre server (maybe this is the problem).  
In server-config.xml I have set issuer to the HTTPS://... url and everything works fine when using the UI (I can log in, navigate around, register clients, ,manage tokens, etc).

Now when I invoke an OAuth flow that has redirects (authorization_code, implicit) the redirects that I get all point to HTTP://... not HTTPS://...   I can't find where these URIs are being pulled from but I assume every URI is built off the issuer so they should be HTTPS.

Any help is greatly appreciated, hoping it's just a config issue.

**Comment by jricher** [comment]
All the URIs in the system are in fact built off of the issuer, so those should always be HTTPS. It's possible that your load balancer configuration is doing some translation of redirects or other URLs going through in requests and responses. It probably all depends on what exactly you're deploying. There was an issue here (now closed?) where someone was getting redirected to HTTP from HTTPS because of the way their reverse proxy was interacting with the system.

**Comment by jtaylor10** [comment]
Just for anyone else who may encounter this problem. They key is config on your web-container which is hosting the app when behind a reverse proxy. If using the spring built-in tomcat you need to follow details at http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server

If using tomcat outside of spring, then add this to either the app web.xml or tomcat's global web.xml: https://tomcat.apache.org/tomcat-8.0-doc/config/filter.html#Basic_configuration_to_handle_'x-forwarded-for'_and_'x-forwarded-proto'

Issue resolved with this config of the container
