### ISSUE TITLE
Issue with mysql

### ISSUE THREAD

**Issue by vsapram** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1138]
I am always getting these exceptions.

Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: PROCEDURE auth.IDENTITY does not exist
Error Code: 1305
Call: CALL IDENTITY()
Query: ValueReadQuery(name="SEQ_GEN_IDENTITY" sql="CALL IDENTITY()")

AND

Oct 27 11:14:06 DEBUG .web.servlet.DispatcherServlet render                    Error rendering view [org.springframework.web.servlet.view.JstlView: name 'home'; URL [/WEB-INF/views/home.jsp]] in DispatcherServlet with name 'spring'
javax.servlet.ServletException: javax.servlet.jsp.JspTagException: No message found under code 'home.title' for locale 'en'.

I am using version 1.2.6. Is there any solution?

**Comment by jricher** [comment]
The first sounds like you've either got the database schema loaded incorrectly or the database connector configured wrong.

The second one sounds like you're building and deploying the webapp incorrectly. 

Neither of these look like problems in the project itself. Look at whatever changes you've made in your instance or overlay.

**Comment by vsapram** [comment]
1) Can you please specify the mysql suppported version and the db engine type?
I am using Mysql 5.6 Innodb engine. 

2) I am using password flow, there is no UI  involved in the applicaion, but still i am getting tag exceptions. Is there any other settings that i have to follow to avoid tag exceptions.

**Comment by jricher** [comment]
1) Supported versions and setups all depend on the connector that you're using. The project itself uses JPA as an abstraction layer to let you replace the underlying database with very little change. This has been deployed into production on several versions of MySQL with different setups. I don't know the exact version numbers and configurations supported, but it should be flexible. You do need to have transaction support enabled.

2) First, be careful using the password flow. It's highly not recommended for security reasons, and it's not even defined for use with the OpenID Connect protocol for those reasons. Avoid it when you can in favor of the authorization code flow. Even then, the error you're getting sounds like you're not building or deploying the server's .war file correctly.

Both of these issues don't show up in the base project as configured, so the error has to be in something that you've changed in your deployment. That's why I encouraged you to look at what you've done to find out what the difference is.

**Comment by vsapram** [comment]
1) while running mysql table scripts, i am getting an error with varchar(2048). I am using mysql 5.6. 
Is there any solution for this?
As i mentioned earlier app is looking for an stored procedure or function like ("CALL IDENTITY()"). But when i look into the resources db folder,  there no script for stored procedures or functions

**Comment by ericgravelle** [comment]
@vsapram  Subsitute VARCHAR for TEXT  Anything above 254 will need to have this done to them.  From our testing, there hasn't been any issues caused by this.

**Comment by vsapram** [comment]
I have done what ever you suggested everything went fine. Authentication also happening. While persisting access tokens in to database , it is always giving this exception.

Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: PROCEDURE auth.IDENTITY does not exist
Error Code: 1305
Call: CALL IDENTITY()
Query: ValueReadQuery(name="SEQ_GEN_IDENTITY" sql="CALL IDENTITY()")

If i look in to db scripts, there is no scripts related to procedure.

Can any one suggest what should i do?

**Comment by jricher** [comment]
I've just built and deployed against MySQL and I can't replicate this problem. I didn't have to make any changes to the code or to the MySQL server (5.6) default setup.

**Comment by lhoekenga** [comment]
@vsapram - did you ever resolve this?  I'm seeing the same thing.

**Comment by vsapram** [comment]
yes. The problem is in data-context file. You need to put proper mysql configuration. Can you add your data-context.xml

**Comment by lhoekenga** [comment]
I'm encountering MitreID as part of a maven overlay to the Shibboleth IDP, but I think I found the place to set this value there (in system/conf/oidc-protocol-storage.xml):

    <bean id="jpaAdapter" class="org.springframework.orm.jpa.vendor.EclipseLinkJpaVendorAdapter">
        <property name="databasePlatform" value="org.eclipse.persistence.platform.database.MySQLPlatform" />
        <property name="showSql" value="true" />
    </bean>

**Comment by vsapram** [comment]
Your configuration seems to be right. In my case i was pointing to wrong platform. So i see that error.
