### ISSUE TITLE
Using PKCS12 instead of JWKS

### ISSUE THREAD

**Issue by dbschmich** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1156]
What would be the approach to provide an implementation to the project, using a X509 certificate and it's keyset in a PKCS12 instead of an unprotected JWKS file?

**Comment by jricher** [comment]
You'd need to change out the KeyStore implementation to read X509 files. But remember, you'll need to publish the keys as JWKs from the server's endpoints, still. 

Also, I want to note that the server used to use certificates for its key set years ago, but we switched the implementation intentionally. While you call out the JWKs file as "unprotected", in my experience most "protected" keystore files on a server have a password, and that password is configured into the server so that it is opened automatically at start up. That password is usually stored right alongside the key file, making it just as secure as having the keys in an open format like JWKs to begin with. Instead of pretending that the keys are more secure than they really are, we just put them in the file and tell people to protect the file from being read by unintended parties.

**Comment by dbschmich** [comment]
OK, that actually looks quite simple. If I would just change `initializeJwkSet()` to do instead of `jwkSet = JWKSet.parse(s)` to `JWKSet.load(keystore, pwLookup);` with Version 4.33 of the Nimbus JOSE+JWT library. The result is still a JWKSet so even the endpoints should still work, right?

Regarding the JWKs plain text vs. keystore discussion I agree with you. But our company policies force us to have it in a "protected" keystore and put the password to access the keystore as well as the private key into our HSM.

Thanks for the support.

P.S. would you want a upstream push of the implementation?

**Comment by jricher** [comment]
That would work, yes. We'd be glad to look at a pull request -- I would make the X509 version a different class though, so the configuration can swap out the bean implementation. Feel free to pull out common bits into an abstract class if there are any worth saving.

An alternative idea: How long of a string can you store in the HSM? Because you could just store the entire JWK set in there. It would be both more secure as well as more policy compliant. Then you'd need an implementation of the keystore class that would read from that instead of from a file on disk.

**Comment by dbschmich** [comment]
Good idea regarding the JWK in the HSM. Let me analyze this on our side.

**Comment by edmundday** [comment]
@dbschmich did you implement this? I need to do a similar thing.
