### ISSUE TITLE
Response Code 302 (redirect) when sending a POST request with a Bearer Token value 

### ISSUE THREAD

**Issue by claudefalbriard** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1193]
I'd like to authenticate the access to services at the back-end using an HTTPS secured REST POST request. The back-end was enabled with the MITREID Connect Client (OIDC client) and the authentication of the protected resource was successfully tested with a web browser access..  

At the MITREID Connect client, Is there any further configuration required in order to trigger an /introspect call and authenticate the request identified by a Bearer token using a valid access token, according to RFC7662.   

This question extends the topic described in report Github issue 1172 
[ here ](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/1172) 

Is a documentation available that shows the format of the request and headers and the MITREID configuration settings required to enable a Bearer token propagation? The Bearer token authentication is planned to be used between the web portal and the back-end server. 

Thanks in advance for your guidance. 

Regards, 
Claude

**Comment by jricher** [comment]
You're getting a 302 probably because you've set up the OIDC client, which is meant for interactive user login. Just like we mentioned in #1172 you need to set up an OAuth protected resource, not an OIDC client. You can do that using the introspecting token services module wired into the Spring Security OAuth resource filter.
