### ISSUE TITLE
Using an existing User table for User and UserInfo

### ISSUE THREAD

**Issue by lxblvs** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1208]
Apologies for a potentially stupid question.

How to configure the authentication to authenticate against an existing User table (and specify the password hash method etc)? We also have most of the UserInfo stored in the same table and would like to access it from there.

Thank you!

**Comment by jricher** [comment]
Not a stupid question, this is a very common deployment of the project. If you've got an existing user store, you'll just need to map the authentication in Spring Security against that store (see the Spring Security docs for details). To get UserInfo out of that same table, you'll want to implement your own UserInfoRepository that maps your database objects to UserInfo objects, either DefaultUserInfo or a subclass thereof most likely. All of this is traditionally configured in `user-context.xml`.

**Comment by aliiitarek** [comment]
Hello Justin,

I am trying to use a login endpoint to authenticate the user login. Upon login from this endpoint, I get all the data I need to populate the UserInfo object. 
The rest of the flow -verifying the client and storing the token information and everything else- should be stored in a mysql database with the schema in `mysql_database_tables.sql` so should be the same as the base project.

I am sadly a newbie with spring security.

I implemented a `customFilter` + `customAuthentication` + `customAuthenticationProvider` + `customUserDetails`. 

In the `customFilter`, I get my `customAuthenticationProvider` to authenticate the request. I fill the `customAuthentication` with my `customUserDetails`. Then fill the `SecurityContextHolder.getContext().setAuthentication()` with the returned `customAuthentication` object. This -if I understand correctly which I might not-  makes the `customUserDetails` in the `customAuthentication` which can be accessed by getting this authentication object from the `SecurityContextHolder` 

Clarifying Questions:
(0) Should I store the `customUserDetails` in the `user_info` table to persist this data?
(1) Since I have my user's passwords somewhere else and I am logging in using a personal login API endpoint, I no longer need the `users` table, right?
(2) How do I configure my user-context.xml to just use these custom [Filter and Provider] to authenticate the user in the login page, but get the client information and any other required persistent information from a I created database with the schema as in `mysql_database_tables.sql`?
(3) As per your above comment, do I need to implement a `Repository`? I don't have direct access to my database, I can login a user from a login-endpoint. and upon login I have a Json object containing all the user information that I would possibly need. How do I map this Json User object with your server `UserInfo object` to make everything work. 

I again apologies if my lack of understanding of Spring security made me ask this question although it is obvious.

This is my user-context.xml:

`<bean id="customAuthenticationProvider" class="com.authentication.CustomAuthenticationProvider"/>

	<bean id="customFilter" class="com.authentication.CustomFilter">
		<property name="authenticationManager" ref="authenticationManager" />
	</bean>

	<security:authentication-manager id="authenticationManager">
		<security:authentication-provider ref="customAuthenticationProvider" />
		<security:authentication-provider>
			<security:jdbc-user-service data-source-ref="dataSource"/>
		</security:authentication-provider>
	</security:authentication-manager>

	<mvc:view-controller path="/login" view-name="login" />

	<security:http authentication-manager-ref="authenticationManager">
		<security:intercept-url pattern="/**" access="permitAll" />

		<security:form-login login-page="/login" authentication-failure-url="/login?error=failure" authentication-success-handler-ref="authenticationTimeStamper" />
		<security:custom-filter ref="authRequestFilter" after="SECURITY_CONTEXT_FILTER" />
		<security:logout logout-url="/logout" />
		<security:anonymous />
		<security:expression-handler ref="oauthWebExpressionHandler" />
		<security:headers>
			<security:frame-options policy="DENY" />
		</security:headers>
		<security:csrf />
	</security:http>

</beans>`
