### ISSUE TITLE
Implicit flow question: unsupported_response_type: "id_token"

### ISSUE THREAD

**Issue by Gurkenschreck** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1226]
Hello everyone,
I am using the MITREid Connect server in combination with the implicit flow.

When the session_check_iframe (which is embedded by my client) detects a session change, it tries to call the authorization endpoint with response_type id_token to query the session status. The server responds with unsupported_response_type: 'id_token' and the log says:

```
2017-04-04 11:18:44,746 INFO  (ajp-nio-127.0.0.1-8009-exec-26) [AuthorizationEndpoint(handleOAuth2Exception:516)] Handling OAuth2 error: error="unsupported_response_type", error_description="Unsupported response types: [id_token]" 
```

I didn't find much info about this, the google results were not satisfying. In the server configuration of this client, the grant type is set to "implicit" and the response types to "id_token" and "id_token token" (with the info "Not Yet Implemented" to the right of "Response Types"). 

Question: Is the implicit flow completely implemented as specified in the OpenID Connect specifications?

Thank you for your time

**Comment by jricher** [comment]
We don't currently fully support the implicit flow as specified in the OIDC specification due to some limitations with an upstream library that's been on the chopping block for a while but hasn't fully been excised yet. We do support the implicit flow by having the client send a request for `response_type=token` with the `openid` (and other) scopes. This is the vanilla OAuth implicit flow, and you'll get an ID token by nature of the `openid` scope's presence.

**Comment by Gurkenschreck** [comment]
Ok, good to know. Thank you for your response.

**Comment by Treehopper** [comment]
Maybe I'm missing something, but it is not required to implement support for the id_token in the implicit flow, in order to implement OpenID Connect Core 1.0?
I also see that the error returned ('unsupported_response_type') is not standardized.
Should this ticket be re-opened?
