### ISSUE TITLE
Can I redirect user after failed authentication?

### ISSUE THREAD

**Issue by jirmauritz** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1241]
Is it possible to redirect a user to a custom page after failed authentication (AuthenticationFilter returns null)? Right now, we are seeing Error:403 Forbidden page.

**Comment by jricher** [comment]
On the server, or using the client's filter? I'm going to assume you're asking about the client because the server should automatically send you back to the login page by default.

You need to set up a login failure handler in your application and have it go to the right page. This is Spring Security configuration and isn't specific to the mitreid project.

**Comment by jirmauritz** [comment]
Yes, I meant client's filter. OK, that makes sense, I will look into the Spring Security documentation.
