### ISSUE TITLE
Support resource owner credentials grant or not?

### ISSUE THREAD

**Issue by chenshengxiong** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1243]
Hi 
Do we support resource owner credentials grant of OAuth2, the grant_type value is password, if yes, can you give a client request example.

**Comment by jricher** [comment]
Yes, the server supports toss grant type. A client has to be specially enabled to use it on the registration page. The request is conformant with the spec. 

This grant type is largely not recommended in practice as it carries huge security risks. It's almost always better to use the authorization code grant type and have the user log in directly to the server instead of stealing their password.

**Comment by chenshengxiong** [comment]
Got it, Thank you for your guidance!
