### ISSUE TITLE
Bug- The framework shows successful authentication when login fails

### ISSUE THREAD

**Issue by ioprescu** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1247]
The method onAuthenticationSuccess gets executed and the application logs "Succesfull Authentication". However the login fails on ConnectTokenEnhancer with an invalid message such as "Request for ID token when no user is present".  This is definitely not the issue as the data was present when we got this error.

The real issue is that the access token insertion in the database fails with a truncation error.

See below:

```
o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: JpaSystemException, Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.DataTruncation: Data truncation
Error Code: 0
Call: INSERT INTO access_token (expiration, token_value, token_type, auth_holder_id, client_id, refresh_token_id, id_token_id) VALUES (?, ?, ?, ?, ?, ?, ?)
    bind => [7 parameters bound]
Query: InsertObjectQuery(org.mitre.oauth2.model.OAuth2AccessTokenEntity@70eadbf1); nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): 
```

The database is a SQL Server. The generated token was longer than 4k. We have fixed this by increasing the column length but this is not fixing the root cause.

**Comment by jricher** [comment]
The user logs into the IdP before the OIDC transaction can take place. The authentication and login were in fact successful, the logs are correct. What might be misleading from your perspective is that the downstream login to the RP didn't happen, but that's not what the authentication success is referring to.

4K Seems *REALLY* big for a single token to me, do you have a custom token generator that adds additional fields? Though I suppose with RS512 or other large signature methods it could get big -- so any details you could add would be helpful.

As for the truncation, MS SQL Server is going to need a custom schema anyway. The error displayed  happens when the server can't find an appropriate UserInfo object for the current user and is not directly related to the truncation error. If you log to the IdP in as the user in question, can you see the user's attributes in the "Profile" section of the UI?
