### ISSUE TITLE
AuthorizationRequestFilter creates a session for each request 

### ISSUE THREAD

**Issue by duffdodger** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1290]
AuthorizationRequestFilter calls `request.getSession()` before request match checking, that causes creation of new session if it doesn't exist (in case stateless token endpoint, for example).

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/ef01d3032e3147e69783e32843672f688a8b25c4/openid-connect-server/src/main/java/org/mitre/openid/connect/filter/AuthorizationRequestFilter.java#L108

**Comment by jricher** [comment]
This filter doesn't fire on the token endpoint -- or at least it shouldn't. It should only be tied to the authorization endpoint.

**Comment by SantoshKumar4** [comment]
Hi,
Need your suggestion on a related topic.

After successful authorize request processing, I want to clear/end the session. I am looking for this behavior so that user completes the authentication process on every authorize request,  but if user logs in to the admin site then he should continue to retain the session until he logs out. 
What is your opinion on this?

Thanks

**Comment by jricher** [comment]
@SantoshKumar4 Don't comment on issues with a new question or topic, please start a new one. That said, sounds like you want to have the RP pass `prompt=login` to the server in the authorization request. This doesn't log the user out but it does force them to log back in, which might be the results you're really after.
