### ISSUE TITLE
Registration Access Token without User Auth

### ISSUE THREAD

**Issue by r3dlin3** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1307]
Hi,

After creating a registration access token, I have in the database a Authentication Holder without User Auth Id (the column user_auth_id is null).
It does not seem clean to have an authentication holder without an associated user.
I guess the line to blame is:
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/ef01d3032e3147e69783e32843672f688a8b25c4/openid-connect-server/src/main/java/org/mitre/openid/connect/service/impl/DefaultOIDCTokenService.java#L263

Not sure how to fix this as the Controller DynamicClientRegistrationEndpoint is the one knowing the authenticated user.

**Comment by r3dlin3** [comment]
My concern is that in DefaultOAuth2ProviderTokenService for instance, we have code like (cf. [DefaultOAuth2ProviderTokenService](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/ef01d3032e3147e69783e32843672f688a8b25c4/openid-connect-server/src/main/java/org/mitre/oauth2/service/impl/DefaultOAuth2ProviderTokenService.java#L113))
```
for (OAuth2AccessTokenEntity token : all) {
	if (clearExpiredAccessToken(token) != null && token.getAuthenticationHolder().getAuthentication().getName().equals(id)) {
		results.add(token);
	}
}
```
Would not that results in a NPE as there is no authentication and no name associated with the token?

**Comment by jricher** [comment]
No it won't. The underlying call to GetName calls this function:

https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/authentication/AbstractAuthenticationToken.java#L81

Which is already null safe even if the principal is null, which it won't be because of the implementation of getprincipal here:

https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/OAuth2Authentication.java#L38

**Comment by jricher** [comment]
To be clear: the authentication holder in this case isn't associated with any specific user, but was instead issued on behalf of the client itself which is now registered to and associated with that token per the constructor call above.
