### ISSUE TITLE
Questions for OpenID-Connect developers comparing to Cloud Foundry UAA

### ISSUE THREAD

**Issue by anthonys123** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1400]
Hello All - I'm in the midst of trying to convince a set of developers that OpenID-Connect should be used instead of Cloud Foundry's UAA for a SMART on FHIR health-care application.  They have raised the following objections to OpenID-Connect and I would appreciate any input on if these are correct or not:

- OpenID-Connect stores client secrets and user passwords in plain text which have been a discarded practice for long time. UAA from Cloud Foundry has been deployed in production particularly as part of Cloud Foundry PaaS.

- The wild card scope handling (e.g. patient/*.*) in MITRE is less secure than in UAA. In UAA, the wild card scope means all the specific scopes specified at the client registration, it is will NOT include any specific scopes which are not specified at the client registration, it is used as convenient way for a client to request specific scopes already specified. In MITRE, it really goes wild: there is no need to specify specific scopes.

Many thanks in advance.

**Comment by jricher** [comment]
OpenID Connect doesn't say anything about storing client secrets or user passwords, it's an implementation issue. This implementation (MITREid Connect) does store client secrets in plaintext, but that's because they are not chosen by users, not repeated in other systems (unique to the client/AS pair), and contain sufficient entropy so as not to be guessed by an attacker. Additionally, OpenID Connect (and this implementation specifically) also allows for key-based authentication.

Neither OpenID Connect nor this implementation support "wildcard scopes". If you don't specify a scope on registration you can request any scopes, but that functionality could be easily turned off in a customized deployment. Dynamically registered clients get the "default" scopes.

**Comment by anthonys123** [comment]
Many thanks for the reply Justin.  A quick follow-up question - is the OpenID-Connect server also intended for use in production environments?

**Comment by jricher** [comment]
The MITREid Connect project has been used in many different production environments, after customization and deployment with a user management system. 

Your second question is better directed at the SMART on FHIR team.
