### ISSUE TITLE
Question: Implicit/Hybrid flow support

### ISSUE THREAD

**Issue by kyvour** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1401]
Hi

Does midreid-oidc server supports implicit flow now? I saw the tickets related to implicit flow, but they all are closed. Is this means that mitreid server fully supports implicit flow?

Also the same question is about Hybrid flow. As I far as understood mitreid server is based on spring-security-oauth2, and I think it does not support Hybrid flow. Am I right?

**Comment by jricher** [comment]
The server supports the OAuth implicit flow (`token` response type), but does not support the OIDC implicit flow (`token idtoken` response type) or any of the OIDC hybrid flows. This is due to limitations in the spring library that you mentioned. There has been a long desire to remove that library but nobody has been able to invest the time and effort into doing so in the project yet.

**Comment by athulrl** [comment]
Could you please confirm whether midreid-oidc server has any recent changes for support implicit or hybrid flow? Or still it doesn't support those?
