### ISSUE TITLE
Client side filter for checking access_token expiration and refreshing 

### ISSUE THREAD

**Issue by rhinmass** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1460]
Hello, 

Just trying to figure out if there is support in the client framework for setting up a filter to 
- check if the current access_token has expired
- if so use the refresh token to get a new one
- if that fails redirect to login

Is this a filter we need to develop from scratch, or is there something in the framework that we can make use of.

Sorry for the newbie question.  I couldn't find any documentation on it.

**Comment by jricher** [comment]
The MITREid Connect client library does not include that functionality automatically at this time since it focuses on OpenID Connect login and not on OAuth2 API access, which is what you'd need a long-term access token for.

Also, please note that the lifetime of the access token, the lifetime of the ID token, and the lifetime of the user's session (being logged in) aren't the same.

**Comment by rhinmass** [comment]
Answering my own question, for anyone in the future who stumbles over this:

```
		SecurityContext sc = SecurityContextHolder.getContext();
		OIDCAuthenticationToken auth = (OIDCAuthenticationToken) sc.getAuthentication();
		
		String accessToken = auth.getAccessTokenValue();
		String refreshToken = auth.getRefreshTokenValue();
```
