### ISSUE TITLE
How to disable consent screen after login ?

### ISSUE THREAD

**Issue by vinayakbhadage** [mitreid-connect/OpenID-Connect-Java-Spring-Server#775]
Hi,

I am using IDP for trusted sub system. Only trusted relying party going to login into IDP. In this case I want to hide the Consent Screen which appear after login.

 Would you please let me know how to disable it.

**Using following configuration from Relying Party**
	 
	<bean class="org.mitre.openid.connect.client.service.impl.StaticAuthRequestOptionsService" id="staticAuthRequestOptionsService">
	        <property name="options">
	            <map>
	                <entry key="display" value="page" />
	                <entry key="prompt" value="login" />
	            </map>
	        </property>
	</bean>

Thanks & Regards,

-Vinayak

**Comment by jricher** [comment]
Two things,

First, you don't disable the authorization step, but you can whitelist a trusted site and set of scopes. Log in as the administrator, go to the client management page, find the registration entry for the trusted client (since it's a trusted sub system I'm going to assume it's statically registered), and click the "Whitelist" button. This will let you pick a set of scopes for which users will not be prompted. They'll still need to be logged in to the IdP and they'll still technically be going to the authorization page, the only difference is that no HTML will render before they're redirected back to the client.

Second, if you're really passing that from our client library, then it's going to cause our server to force a new login for every request. That may or may not be what you actually mean to do.

**Comment by vinayakbhadage** [comment]
Thank you Justin for quick reply. I will try the first option and get back on it.
