### ISSUE TITLE
How to get target URL for RP after redirection through IDP ?

### ISSUE THREAD

**Issue by vinayakbhadage** [mitreid-connect/OpenID-Connect-Java-Spring-Server#776]
Hi,

The scenario is like below:

1. The user trying to access some resource from Relying party.

		e.g http://www.relying-party.com/#/user?id=23456789

2. Now relying party session is unauthenticated so it will be redirected to IDP for login:
		
		1. http://www.idp.com/authorize?redirect-uri=http://www.relying-party.com/&....... etc
		On login page url is like this
		2. http://www.idp.com/login#/user?id=23456789
		
3. then IDP gives the code to a relying party and relying party fetch the access token and come back to home page.

		1. http://www.relying-party.com/code=asdsadsadsa&state=XXXXXX
		Now browser is showing the home page
		2. http://www.relying-party.com

In this case user is lost the requested page, Ideally he should be on the requested page 

		i.e. http://www.relying-party.com/#/user?id=23456789

actually the spring security handle this but we lost it in IDP.

Would you please let me know how to support this situation ?

Thanks & Regards,

-Vinayak

**Comment by jricher** [comment]
The fragment portion of the URL (following the #) will be stripped in the redirection process, for security reasons. You generally do *not* want to pass a deep link as a return URL, and usually don't inside of a query parameter anyway, as this can lead to open redirector situations. What you actually want to do is have your client app save its state in a local session before it starts the login process, then pick it up out of that session when the login returns and continue on your way.

Spring Security does this for you automatically, and it's actually doing that here, it's just that your RP has a semantically significant fragment portion that is *not* being saved by Spring. In fact, Spring can't do this for you because it doesn't see the fragment portion -- that's all browser side and doesn't even get sent in the HTTP request to the server (that is, the relying party server).

**Comment by vinayakbhadage** [comment]
Yes, you are right. it needs to handle in the RP. 
Need to check how to do this?
