### ISSUE TITLE
Additional arbitrary scopes

### ISSUE THREAD

**Issue by ngriesser** [mitreid-connect/OpenID-Connect-Java-Spring-Server#783]
Client and Server support additional arbitrary scopes.
Is there any documentation on how to add some?
Where can these additional scopes be configured?

**Comment by jricher** [comment]
That depends on what you mean by configured. If you just want to register a client with additional scopes, you can do that through the server's admin interface under "manage clients" and the "access" tab. If you want there to be a system-wide scope available, then you can add that in the "system scopes" section in the admin console. For the client, just add the scopes you want to the client's registration record.

Note: for version 1.0 and 1.1, you need to explicitly set the "allow dyn reg" flag on scopes in order to let dynamically registered clients use them. For 1.2 (current master branch) you don't have to do that but instead can set certain scopes as "restricted" allowing only an admin to use them. In either case, an admin can register a client with whatever scopes they choose.

**Comment by ngriesser** [comment]
Is it possible to add claims related to a new scope?

**Comment by jricher** [comment]
Yes, but not through the current UI. You'll need to override a number of classes, including UserInfo and the associated views/assemblers that translate the scopes into claims. There are plugs to allow this kind of customization though.

**Comment by ngriesser** [comment]
Ok, I just wanted to make sure there was no simpler way.
Thank you.
