### ISSUE TITLE
OIDC Behaviour

### ISSUE THREAD

**Issue by VinothrajaJ** [mitreid-connect/OpenID-Connect-Java-Spring-Server#806]
Once I sucessfully login to my app1 through OIDC through implicit code flow, i receive my tokens(id,access,refresh). 
I try to login to app2 through OIDC and follow same steps as above i get differerent sets of tokens(all together).
 The issue is I am able to interchangeably use my app 1 access token to get my userInfo from app2. This is also applicable when I try to get access token with refresh token.
Additionally, when i try to access userinfo with access token from different browser(without even logging in) my OIDC grants me the information.
There is no session binding between the tokens issued..? are all those behaviour expected.?

**Comment by jricher** [comment]
The access tokens are bearer tokens: whoever holds the token holds the ability to use it. That's the intentional design. The solution here is to not share access tokens between your applications if you don't want them to leak. It also shows you that you can't count on the presence of an access token to tell you anything about the user logged in. The access token has nothing to do with the user's browser session, and it's used in the background to access the userinfo information. This is the core pattern of OAuth, actually, and it's all intentional: it's generally meant to be used when the user is not present at the client application anymore. 

In order to have a login, you need to use a construct like the ID token that comes with OIDC. For the ID tokens, you should be checking the `aud` field (audience) for your client's client ID. If your client ID isn't in the `aud` field of the ID token, then you shouldn't be accepting it for login.

Hope this helps clear things up.

**Comment by VinothrajaJ** [comment]
Thanks for the quick response jricher.. I clearly understood the purpose of access token. Same behaviour is expected from refresh token as well. 

In case of implicit flow (purely browser based app), tokens are supposed to be saved in local storage. Losing access token would only expose the service(protected resource) and userinfo(OIDC endpoint) for short time being. If refresh token is lost , we would be exposing the resources for  a long duration.

Assuming my above assumptions , can i conclude offline access is recommended for implicit code flow?

**Comment by jricher** [comment]
Actually, `offline_access` is explicitly forbidden in the implicit flow: you can't get a refresh token from that flow at all.

**Comment by VinothrajaJ** [comment]
Thanks jricher...I am trying to implement SSO solution for a list of apps which includes both  web apps, native apps . As per oauth2 spec, access tokens can not be given more than 1 hour to access the protected resource. If openid spec does allow me to have offlice_acces implicit flow, should i go for gateway(web server layer)  and enforce authorization code flow even for native apps?Any suggestion for this use case can be very handy..?

**Comment by jricher** [comment]
The access tokens can last as long as you want, the OAuth2 spec doesn't specify restricted lifetimes. What you're reading is a general recommendation. With an implicit client, you're looking at something that's sharing a live browser session, so it's really, really easy to just go back to the authorization endpoint and get a new access token because the user is still there. But you can also make the access tokens last longer. The tradeoff is always liveness and security here.

**Comment by jricher** [comment]
Also note that refresh token or access token doesn't really tell you if the user is still there for SSO purposes, you'll want a fresh ID token for that case anyway. But if all you need is to log a user in once to an app, and then have the app "remember" that user as logged in from then on without checking with the server, then just read in the ID token. Finally, you shouldn't be using the implicit flow for native apps: use the code flow instead.

**Comment by VinothrajaJ** [comment]
Thanks jricher..i understood the purpose of id token clearly.. But what if id_token is expired..do we have mechanism in OIDC to refresh Id_token..

**Comment by jricher** [comment]
My question to you is: why do you want to refresh an ID token? What are you trying to accomplish with that? If you're doing it through the back channel (like with a refresh token), then there's no guarantee that the user is logged in to the IdP still when that happens. You're better off fetching a fresh ID token, especially if you've got an implicit client like you've described above: just send them back to the authorization endpoint again.

**Comment by VinothrajaJ** [comment]
Let me put my use case in better way.. I have multiple clients which are registered in OIDC with Implicit grant type as they are browser running. I need a SSO solution to be implemented with atleast 12 hours of sso_session(user activity should not be interrupted in any of logged in client application) .I don't want to give more than 10 minutes life for my access token.
Can I implement the same using Openid connect specification with mitreid implementation.

I understood my question is too broad, simply putting i have a problem with understanding life cycle of these attributes say access_token,id_token,refresh_token(in case on auth code),code(in case on auth code).

plus if i can get the id_token by calling authorize endpoint, can this be applicable to access token as well.?

**Comment by jricher** [comment]
Why don't you just use a cookie with a 12-hour lifetime in your applications, then? The ID token is what performs the initial authentication of the session, but after that it's up to the application to manage its login. Each of your apps is going to be getting a separate ID token anyway, since you don't want them to be able to masquerade as the user with each other. You can do this by simply making a normal request to the authorization endpoint. If the user is still logged in to the IdP and has already authorized the app (or it's whitelisted) then they won't even notice the redirect.

If you want to make sure the same user is still logged in to the IdP apart from your app's session management, then you'll need to send them back to the authorization page to get a new ID token, just like you did the first time through (as described above). And yes, when you do that, you can also get a new access token in the process. The access token doesn't tell you that someone's logged in, just that you got access to the protected resource somehow.

**Comment by VinothrajaJ** [comment]
Thanks jricher..I was blindfolded by the assumption, client do always need refresh token to refresh access token..thanks a ton for making it clear....

**Comment by VinothrajaJ** [comment]
My client is registered for authorization code flow , when i pass this request 

Please clarify this as well..
case 1
GET /authorize?
    response_type=code%20token
    &client_id=s6BhdRkqt3
    &redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb
    &scope=openid%20profile%20email
    &nonce=n-0S6_WzA2Mj
    &state=af0ifjsldkj HTTP/1.1
  Host: server.example.com

I get a error message saying client is not registered for implicit grant type.

case 2
I make my client to be configured for implicit and authorization code(hybrid)

now in my response , i get code,access token and id_token, even though  i requested only for code and access token..

PLease throw some light above two cases..

**Comment by jricher** [comment]
You're asking for a "code token" response type, which actually shouldn't be supported by the current software at all, unless I'm mistaken (or there's a bug). If you ask for one or the other, it should work though, as long as the client is registered for that grant and response type. We recommend that clients only be registered for one response type or another, and not both simultaneously, as this could lead to an unintended downgrade attack on security.

**Comment by VinothrajaJ** [comment]
The above sample is taken from openId specification and also we do have this option to be selected during client registration in MitreId implementation.I presume this to be a bug in implementation side..

**Comment by jricher** [comment]
Yes, the above is for the hybrid flow. But what is your client actually sending for the `response_type` parameter? Right now we only support the `code` and `token` responses, and you'll get an ID Token with the latter response if you ask for the `openid` scope.
