### ISSUE TITLE
Externalize localhost:8080 urls and context path

### ISSUE THREAD

**Issue by mmoayyed** [mitreid-connect/OpenID-Connect-Java-Spring-Server#847]
urls are hardcoded to localhost:8080/openid-connect-server-webapp. It would be best if these could be referenced via some sort of property in a single spot s mods are easier to handle.

**Comment by jricher** [comment]
They already are: you need to change the value of `issuer` in the `ConfigurationPropertiesBean` class, defined in `server-config.xml` in the webapp project.

**Comment by mmoayyed** [comment]
That's not the only place that needs changing though. There are other jsp files, etc that point to localhost:8080

**Comment by mmoayyed** [comment]
There is also the external login jsp file.

**Comment by mmoayyed** [comment]
...and changing the xml file is not intuitive, because it's, well first of all "xml" :) and it's buried in the app which required a build per tier. It would be best if this sort of thing was externalized out to a property file that while by default was in the webapp context, could be referenced outside of the context as well.

**Comment by mmoayyed** [comment]
Something like:

```xml
    <util:properties id="properties" location="${properties.filepath:/WEB-INF/oidc.properties}"/>
    <context:property-placeholder properties-ref="properties"/>
```

and then you could have ${issue.url:defaultValue} in xml and possibly other places.

**Comment by jricher** [comment]
All the JSP files pull the value directly from the configuration bean. There should be no reference to "localhost:8080" outside of that one bean, anywhere in the code. Have you found a place where that's not true? If so, please point to the file and line so that we can fix that and have it point to the bean as they're supposed to. I can't find any references with a quick search on my end, though. (Note that the reference inside of `external_login.jsp` is only for an example button. We expect that file to be replaced on a real server deployment that uses the UMA capabilities.)

We decided not to use a properties file or other externalization method in the main project because we wanted it to be able to be built and run out of the box with no configuration. If you're going to deploy it, you're going to need to follow the instructions in the project documentation:

 https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Server-configuration

For most real production environments that we've seen, there's a project WAR overlay that takes the `server-context.xml` file and externalizes it out to a known system path outside the project tree, like `/etc/mitreid-connect/server-context.xml` using the spring bean `import` directive. We can't point to such a path or system property and achieve the same flexibility that we currently have in the main project, but of course you're free to configure with external files or properties files in your own system overlay if that fits your environment better.

**Comment by mmoayyed** [comment]
Excellent, thank you for your adequate description. Before I proceed, I want to pitch in that we could always take this conversation over to the mailing list if you feel that's more appropriate. 

Few things come to mind:

1. I completely endorse the policy that things should just run out of the box. At the same time, for consistency and less duplicate config, I'd much rather every piece of config be controlled from a single place. While the JSP is just an example, it would be best if its config was also controlled from the config file that controls urls. Because I'd imagine in a production deployment, the value of the jsp will change just as the value of the xml file will change. So keeping them both to be consistent and controlled from one place only makes sense to me. 

Unless they are supposed to be different, in which case sure, you'd expect me to modify them individually.

2. There is no reason why using a property file or some such would be an impediment to OOTB config. You absolutely *can* point to a system property. This is where defaults come into play. In my example snippet up there, the location of the properties file is first retrieved from an environment variable/setting, and if it doesn't exist and is undefined, the location simply defaults to a path that is *right within the app context* which means things will simply continue to work OOTB. If I wanted to run the app for a different tier because I have a different set of props for that tier, all I needed to do without any rebuilds is run the app with a specific environment setting that tells the code how to find my config and where, re-emphasizing the fact that things will simply continue to work OOTB as they did before.

Using the property file by default also has the advantage of, besides being much simpler to deal with and teach someone about it and it being sort of a best practice, is that I can have my spring config auto reload the context if there is a prop change. There are spring extensions that do this sort of thing and so, if you externalize as much of the config as possible into this prop file with reasonable sane defaults, you'd expose better opportunities for deployers to modify and understand it, easier ways for developers to play around with it (or convert it to a synax that they like) while everything will continue to work OOTB just as they did before and now. 

We have been using this approach with a lot of success, and if you'd like further references I'll continue to find and pass them on to you. 

HTH.

**Comment by jricher** [comment]
I still don't understand what you're saying about the values in the .jsp files -- they are **already** configured using the existing bean. If you don't believe me, go change the value in that bean and watch it change in all of the .jsp files too. There's an interceptor that injects the bean into the context and makes it available for all .jsp processed pages, as the `config` variable. That's why you'll see `config.issuer` in a bunch of places throughout those. Other parts of the code inject the bean with `@Autowired` and use it that way.

As to the rest, I've used properties files on a number of projects in the past, and we don't plan on changing the configuration here to use them, for a number of reasons. You can **already** deploy the same .war file to multiple different tiers and locations without rebuilding it if you externalize your configuration in a localized overlay. This is our recommended practice for building and deploying this server because more often than not it takes much more than just changing a small set of properties. For instance, most production instances of this code are tied to an enterprise SSO system of some type (MIT uses Kerberos, for example), which requires changes to the authorization providers and a few other things that you can't express with a properties file. 

You are, of course, free to implement properties files to handle configurations in your own overlays, and I recommend that you do just that.

**Comment by mmoayyed** [comment]
Great, thanks. 

I guess part of my confusion was that I did change the xml file at first, because I wanted to run the app under a different port, domain and path but I didnt see the external login url change (as it was still pointing to localhost:8080/xyz). I understand it is meant to be changed and is just an example, but as a point of principal, if you intend to provide a single spot whence a single value is controlled, then it should affect and apply to everything, regardless of whether they are meant to be changed let on. 

But I take your point. Fair enough :)

Unfortunately, I am working on a project that will not utilize an overlay concept so that option is out. Nonetheless, I am going to have to come up with alternative means
