### ISSUE TITLE
id_token in implicit flow only contains openid scope fields

### ISSUE THREAD

**Issue by jorispz** [mitreid-connect/OpenID-Connect-Java-Spring-Server#869]
I am implementing a client that uses the implicit flow with the server. I can successfully login and receive an id_token in the response of the implicit flow.

However, when I include other scopes such as profile or email, the corresponding fields are not included in the id_token. The extra scopes do appear on the authorization screen on the server side, so I know the scope request is correct.

Is there a reason why the extra fields don't show up, or is this a bug?

**Comment by jricher** [comment]
This is the intended behavior. Those extra fields are available from the UserInfo Endpoint, which the access token can be used to call. There's a more advanced mechanism for requesting claims inside the ID token, but we don't yet support it (see #473 for some details).

**Comment by jorispz** [comment]
Ah ok, thanks for the answer! Just out of curiosity, is there a particular reason not to include them in the id_token in the first place? It would save a round-trip to the server, no?

**Comment by jricher** [comment]
It makes the ID token larger for values that don't tend to change over time. Most clients will fetch the UserInfo only the first time through and store it somewhere, and you only need the `iss`/`sub` pair to uniquely identify the user. The ID token is generally a place for authentication-event information, but the UserInfo endpoint is for more profile information. So you need the ID token every time, but you don't need the rest of the claims every time because you can cache them, saving trips in the future and saving space on each subsequent transaction. The client won't know if it needs to fetch those extra claims until the transaction is complete, so the IdP would be forced to include them every time. This is how SAML works, and it's cause for lots of technical issues and potential privacy leaks.

However, since implicit clients are entirely in the browser, they tend to not have access to long term storage. This means that they're likely going to have to do both fetches to get all the user information. This is a little inefficient, but you trade that for greater design in the general case. The spec has the claims request mechanism in place just for clients that would like to put everything in the ID token every time, but that's trickier to implement (even though it's on our todo list!).

**Comment by jorispz** [comment]
That makes a lot of sense, thank you for the explanation!
