### ISSUE TITLE
OIDCAuthenticationProvider drops ServerConfiguration from token object

### ISSUE THREAD

**Issue by wikkim** [mitreid-connect/OpenID-Connect-Java-Spring-Server#878]
Why?

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-client/src/main/java/org/mitre/openid/connect/client/OIDCAuthenticationProvider.java#L95-L100

We want to be able to grab the OIDCAuthenticationToken from the SecurityContext and use it for the UserInfoFetcher, but it breaks because the token object that comes out doesn't have a ServerConfiguration on it anymore.

If there isn't a good reason for dropping the ServerConfiguration from the OIDC token object, we can submit a pull request to keep it in.

**Comment by jricher** [comment]
It was dropped because once the information is fetched and cached, you don't need it anymore with a typical application. Plus it's bound to be hugely redundant (and potentially stale) for every user in the system to have a copy of the server configuration for every single login.

The UserInfoFetcher should already be in a context that has the server information, which is exactly where this gets used the first time the user logs in:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-client/src/main/java/org/mitre/openid/connect/client/UserInfoFetcher.java#L57

If you need it at a later stage, I would suggest injecting a ServerConfigurationService bean, since you'll have the issuer and can use that to look up the server info. Note that you won't be able to use the UserInfoFetcher since that's coded to expect the "Pending" version of the auth token.

**Comment by wikkim** [comment]
Ah, thank you for such a thorough explanation. 

Yea, we were trying to use the UserInfoFetcher at a later stage than the initial authentication. We are still able to reuse that code by manually setting the ServerConfiguration onto the token object before calling that method, but that's probably not an appropriate use of that class since it is meant for "pending tokens" as you say.

Alright, thanks again!

**Comment by jricher** [comment]
Also, it looks like you're building against an outdated version of the library. The current release should disallow exactly what you're trying to do.
