### ISSUE TITLE
Strategy for bookmarked login page

### ISSUE THREAD

**Issue by sdoxsee** [mitreid-connect/OpenID-Connect-Java-Spring-Server#901]
Related to https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/875 is the common scenario where a user of an RP bookmarks the OP's login page in hopes to easily log into the RP in the future. In this case, the OP doesn't have the authorize request to prompt the login and is unable to redirect the user back to the RP. What strategy would you suggest for this? IdentityServer3  provides a mechanism to redirect to a URL. see https://github.com/IdentityServer/IdentityServer3/issues/1780

**Comment by jricher** [comment]
I would recommend telling users to bookmark the RP, since the RP is the one that needs to start the log in process. If the RP supports third-party login, the bookmark can even include the IdP's issuer. You don't want to allow arbitrary URLs being passed into a login page, especially external ones, as that would be an open redirector that's subject to all kinds of phishing attacks. You can't bookmark the authorization page since the RP should be sending a `state` variable that's different every time and the RP should be rejecting requests with either re-used or unrecognized values for it.

**Comment by jricher** [comment]
Just thought of something extra: You could have something on the default homepage of the server that started the third-party login process for a set of known clients, which would take care of this. To do that, replace the current "Welcome" text with your own controls that point to the RPs. These RPs would each have to support the third party login extension but after that it would function fine.

**Comment by sdoxsee** [comment]
Great suggestions. I'll give it some thought and try them out. Thanks for taking the time to respond...and quickly!
