### ISSUE TITLE
Can MitreID Connect be used to achieve cross domain sso?

### ISSUE THREAD

**Issue by vcamelas** [mitreid-connect/OpenID-Connect-Java-Spring-Server#907]
This is the scenario:

idp A -> My organization idp, users have sso for all applications inside the organization

The users need to access some applications outside the organization, I want to exchange the id token for another token to access the outside application.

My question: Can MitreID Connect receive id tokens issued by a trusted idp and return tokens to acces other applicaitons?

**Comment by jricher** [comment]
Sounds like you're talking about using MITREid as an STS, and yes, that's possible. You just need to configure the server to also act as an OpenID Connect client. Since the server uses Spring Security and the MITREid client is a Spring Security filter, that all fits together pretty well. 

Only real question is why not just take the external IdP's tokens directly? Why have the bridge?

**Comment by vcamelas** [comment]
I'm just researching. We have a data center and we plan to offer some stuff as a service, those offered applications should be capable of being a part of a SSO environment.
I am analyzing alternatives to achieve that, one of them is to have something that establishes a trust relationship with the different organizations, receives the id tokens issued by them, and allows the users to use the Saas applications.
