### ISSUE TITLE
Where the mitreid-connect oid server and client security keys located ?

### ISSUE THREAD

**Issue by vbhadrir** [mitreid-connect/OpenID-Connect-Java-Spring-Server#920]
I am trying to setup the mitreid-connect oid server and client on separate machines rather than both of them running on localhost for Tomcat 7. I trying to find the location of the security keys that need to in sync between the client and the server for a successful handshake between them. In IBM Liberty Profile server which supports OpenID Connect the keys.jks and ltpa.keys are easily found in the server resources folder. Can someone point me to the folder in C:\apache-tomcat-7.0.64\webapps\openid-connect-server-webapp\ where these keys are located in mitreid-connect oid server and client for tomcat servers ?

**Comment by jricher** [comment]
The keys are stored by default in the `keystore.jwks` file in the server's resources folder. More information for that is available on the wiki page: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Key-generation

You don't have to copy the keys between the client and server in order to use them on separate machines. The server and client both publish the public keys at a public JWK Set URI so as long as the component knows how to read and parse this URI you're fine.
