### ISSUE TITLE
Cleanup of dynamically registered clients

### ISSUE THREAD

**Issue by praseodym** [mitreid-connect/OpenID-Connect-Java-Spring-Server#947]
When using a dynamically registered client in development, every time the development server restarts, a new client is registered. Would there be a sensible way to clean up old, unused dynamically registered clients?

Alternatively, could we devise a method to store (serialize) the dynamic client registration in the openid-connect-client module?

**Comment by jricher** [comment]
There's an issue for cleaning up old clients already: #398 

There's already a mechanism for storing client information on the client side, RegisteredClientService: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-client/src/main/java/org/mitre/openid/connect/client/service/RegisteredClientService.java

Out of the box in the demo config you get one that's set up for in-memory storage. There's also a version that stores it to a file, and one in the UMA server that puts it into the database.

To get the dev server to not reset the DB each time, just point the data source to something else. The easiest thing is to use a file-backed HSQLDB instead of the in-memory one. It should be safe to re-start any number of times, though sometimes it gets into a DB lock and you need to shut down the server and start it fresh.

**Comment by praseodym** [comment]
Cheers! Using the `JsonFileRegisteredClientService` should at least reduce the number of dynamically registered clients. I had missed it before.

I had already configured the development OIDC server to use a file-backed HSQLDB because it makes it easier to inspect the database. Not sure if it possible to connect to an in-memory HSQLDB from e.g. IntelliJ IDEA at all.

**Comment by jricher** [comment]
It's possible to connect to the in memory db but very difficult, since you need to run the inspector from inside the same java image. I've gotten it to work in eclipse using the debugging tools, but it's a pain and not really worth it.
