### ISSUE TITLE
How to connect client to provider

### ISSUE THREAD

**Issue by kowalski92** [mitreid-connect/OpenID-Connect-Java-Spring-Server#962]
Hi,
I'm new at openid. I have 2 project's first is mine project i want to be client works with Google OAuth Client Library for Java, another i want to make openid provider that works with OpenID-Connect-Java-Spring-Server. Can you explain me how it able to unite them

**Comment by jricher** [comment]
What do you mean by "unite them"? Do you mean connect the Google library based client to the MITREid server? To do that, you need to configure them so that the client can connect to the server. If the client library supports dynamic registration, then you should just have to point it at the server. If not, you'll need to register the client and copy the registration information to the client program.

**Comment by kowalski92** [comment]
understood)), Thank you very much
