### ISSUE TITLE
OAuth2RefreshTokenEntity inheritance hierarchy?

### ISSUE THREAD

**Issue by mmoayyed** [mitreid-connect/OpenID-Connect-Java-Spring-Server#979]
Does it make sense for `OAuth2RefreshTokenEntity` to implement `ExpiringOAuth2RefreshToken`?

**Comment by mmoayyed** [comment]
I am trying to pass the token to a method that looks like this:

```
public void storeOAuth2RefreshToken(final ExpiringOAuth2RefreshToken t) {}
```

Obviously, can't.

There is expiration field in `OAuth2RefreshTokenEntity`. It seems to be impl-specific though. If the expiration could be handled in the entity directly by implementing that interface, life would be much easier.

**Comment by jricher** [comment]
The Expiring version of the interface was added in a later revision of the SECOAUTH library, long after we had implemented expiration support for refresh tokens. I would suggest that it's a bug in the library that the storage method require the more strict interface rather than the generic one.

It might make sense for our implementation to have that interface as well, but we're also looking to remove the dependency on this library so I'm hesitant to add further hooks that will need to be un-hooked later.

**Comment by mmoayyed** [comment]
Which replacement library are you moving towards?

**Comment by jricher** [comment]
No library. We've already overridden or replaced most of the functionality in the current library so we would just be replacing the last few pieces with custom code.

**Comment by mmoayyed** [comment]
Cool. I am assuming that also means you'd be moving away from Spring security as well?

**Comment by jricher** [comment]
We don't intend to move away from Spring or Spring Security.

**Comment by praseodym** [comment]
I'm not sure if moving away from Spring Security OAuth2 will be the best move, since they'll most likely be implementing OIDC compatibility as well (client stuff first). Then we'll just end up with two competing libraries.

**Comment by jricher** [comment]
There are already multiple competing libraries on the Java platform (Apache Oltu being another). We're just not using much more of the SECOAUTH library anymore, it's just getting those last few bits pulled out is going to take some engineering and planning.
