### ISSUE TITLE
SAML & SCIM support?

### ISSUE THREAD

**Issue by heditr** [mitreid-connect/OpenID-Connect-Java-Spring-Server#993]
There will be a support for the SAML and SCIM technologies in the road-map of mitreid-connect team?

**Comment by praseodym** [comment]
I don't think there is any interest to go beyond OpenID Connect. You might be better off looking at OpenAM or Microsoft ADFS.

**Comment by jricher** [comment]
We've toyed with implementing a SCIM system along with a user provisioning and management component, but there hasn't been enough demand or drive to carry that out. There are no plans for implementing SAML in the codebase, but I know of at least two instances where teams are building MITREid Connect into a SAML-enabled environment and running things in concert with each other. In fact, that's one of the main strengths of this project: it doesn't need to own your whole identity stack in order to function, unlike OpenAM and ADFS prefer to do.

**Comment by mmoayyed** [comment]
The shibboleth identity provider will soon support openid connect based on mitreid. The CAS project also will have openid connect, and it already supports saml.

**Comment by heditr** [comment]
Ok, Thanks guys for the help.
I think it will be great to add the SCIM support in mitreid-connect project.
