### ISSUE TITLE
Error creating client_details table in mysql

### ISSUE THREAD

**Issue by mpeddagolla** [mitreid-connect/OpenID-Connect-Java-Spring-Server#999]
I am trying to setup schema using mysql_database_tables.sql but creating client_details tables seems to be having a problem. Specified key was too long; max key length is 767 bytes. Default engine is "InnoDB" and collabtion is "utf8-default collation". Is there a work around or am I doing something wrong?

``` sql
    CREATE TABLE IF NOT EXISTS client_details (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    client_description VARCHAR(1024),
    reuse_refresh_tokens BOOLEAN DEFAULT true NOT NULL,
    dynamically_registered BOOLEAN DEFAULT false NOT NULL,
    allow_introspection BOOLEAN DEFAULT false NOT NULL,
    id_token_validity_seconds BIGINT DEFAULT 600 NOT NULL,

    client_id VARCHAR(256),
    client_secret VARCHAR(2048),
    access_token_validity_seconds BIGINT,
    refresh_token_validity_seconds BIGINT,

    application_type VARCHAR(256),
    client_name VARCHAR(256),
    token_endpoint_auth_method VARCHAR(256),
    subject_type VARCHAR(256),

    logo_uri VARCHAR(2048),
    policy_uri VARCHAR(2048),
    client_uri VARCHAR(2048),
    tos_uri VARCHAR(2048),

    jwks_uri VARCHAR(2048),
    jwks VARCHAR(8192),
    sector_identifier_uri VARCHAR(2048),

    request_object_signing_alg VARCHAR(256),

    user_info_signed_response_alg VARCHAR(256),
    user_info_encrypted_response_alg VARCHAR(256),
    user_info_encrypted_response_enc VARCHAR(256),

    id_token_signed_response_alg VARCHAR(256),
    id_token_encrypted_response_alg VARCHAR(256),
    id_token_encrypted_response_enc VARCHAR(256),

    token_endpoint_auth_signing_alg VARCHAR(256),

    default_max_age BIGINT,
    require_auth_time BOOLEAN,
    created_at TIMESTAMP NULL,
    initiate_login_uri VARCHAR(2048),
    clear_access_tokens_on_refresh BOOLEAN DEFAULT true NOT NULL,

    UNIQUE (client_id)
);
```

Thanks
Mallikarjun

**Comment by jricher** [comment]
Interesting, I haven't seen this across the several different MySQL installations I've set up with this server. Are there any other changes that were made? What's the host platform?

**Comment by mpeddagolla** [comment]
I was trying to setup overlay project and deploy to local tomcat. That went through well. Now, I want to replace the existing in-memory database with MYSQL so I was setting up the schema in my local MYSQL server. I just took the provided schema for MYSQL and ran and it throws the error. I am on Windows7 and everything is local.

Thanks
Mallikarjun

**Comment by dan-n-promethean** [comment]
In MySQL the following settings have to be changed to these values. 
(/etc/my.cnf will need to be updated to reflect these settings as well)

set global innodb_large_prefix = ON;
set global innodb_file_format = BARRACUDA;

CREATE TABLE IF NOT EXISTS client_details (
 id BIGINT NOT NULL AUTO_INCREMENT ,
   . 
   . 
   . 
  logo_uri BLOB,
 policy_uri BLOB,
 client_uri BLOB,
 tos_uri BLOB,
 jwks_uri BLOB,
 jwks BLOB,
   . 
   .  
   . 
PRIMARY KEY (`id`),
 UNIQUE (client_id)
) ROW_FORMAT=DYNAMIC;


OR the length of the client_id could be reduced to 255 (from 256).

either way will work

**Comment by jricher** [comment]
Again, I find this strange as I've deployed this directly to MySQL without any special configurations or updates. Is this a version or platform difference that's tripping this up, perhaps some distribution of MySQL sets this by default?

**Comment by dan-n-promethean** [comment]
MySQL InnoDB currently supports two named file formats, Antelope and Barracuda.

Antelope **was the original InnoDB file format**, which previously did not have a name. It supports COMPACT and REDUNDANT row formats for InnoDB tables and **is the default file format in MySQL 5.6** to ensure maximum compatibility with earlier MySQL versions that do not support the Barracuda file format.

Barracuda is the newest file format. It supports all InnoDB row formats including the newer COMPRESSED and DYNAMIC row formats. The features associated with COMPRESSED and DYNAMIC row formats include compressed tables, off-page storage for **long column data**, and **index key prefixes up to 3072 bytes** (innodb_large_prefix).

**Comment by jricher** [comment]
OK, that makes more sense now. I must not have run into the new file format. Thanks for the explanation!

Since we don't change the database schema for patch releases (apart from adding an index now and again), we'll target this for the 1.3 branch when that is started later this year. For now we'll leave this as the official workaround on such systems. Would you be willing to write up a wiki page documenting this, @dan-n-promethean ?

**Comment by praseodym** [comment]
But if Barracuda is not the default format and only available in recent MySQL versions, why has this issue not been triggered in earlier deployments?

**Comment by dan-n-promethean** [comment]
In real life, almost everybody switched to Barracuda, long, long, ago...

**Comment by wangruochan** [comment]
I had the similar problem when I use the' UTF-8' Character set which is common in China.
So I changed the DB Character set to default and it works.

**Comment by morungos** [comment]
Just a comment, don't try using `BLOB`, use `TEXT` in MySQL. `BLOB` fields get transparently converted to hex strings, so secrets never match and you can't authenticate. See the reference from #1175, which was a consequence of this strategy.

**Comment by jricher** [comment]
I just built and deployed against MySQL and I did not run into this problem. I was able to use the MySQL database schema file with no alterations.

**Comment by morungos** [comment]
Well, it sadly depends on the version of MySQL and how it's configured. If you are using a newish version with InnoDB enabled as default, it won't work. An old version, or configured not to use InnoDB, and you're probably good. See the earlier comment at: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/999#issuecomment-176964696 which summarizes it nicely. 

However, I'd comment that this isn't great DB design anyway. There's almost never a need for a full index on 256 characters, especially when in UTF-8. A prefix index would also solve the problem and be easier on a server (not that there's ever going to be a huge table of client ids). 

The problem is essentially that MySQL uses a lot of server defaults, which will be entirely different between deployments, and these fundamentally change settings which will break a schema. It's a good idea to be more explicit, either setting session defaults or table settings which are more sensible. Can a JWKS ever be UTF-8? Or a client key? I'm not that standards-aware, but I'd be surprised. If not, these fields can be better encoded anyway. 

Sorry for the long exposition, I'm deploying this alongside another app with the exact same issues -- I've been given a MySQL deploy I have zero control over, and therefore have to work around whatever the installer did when they set it up. This is not an unusual case. And it is very easy to resolve. 

And I can't see any good reason why un-indexed large text fields can't be `TEXT`, at least for MySQL and similar, i.e., do they really need to be stored in-row?

**Comment by jricher** [comment]
The MySQL instance that I used in this case was the "mysql/mysql-server" docker image, which gives me MySQL 5.7. I understand there's a lot of variability of the database deployment, but I try to make it work at least on the "install the database package and go" setup for common environments.

I'm fine with tweaking the database schema if it really does make sense to do so, so long as making one change here to fit your setup doesn't break other setups. If that means changing existing indexes to prefix indexes or changing field types from VARCHAR to TEXT (as you suggest in a few spots) then that's fine, so long as it doesn't break other installations. We're in a period of being able to change the schema prior to the 1.3 release, so if you can provide a pull request with the appropriate changes and test it on a few different environments, I'd be happy to pull it in.

FWIW, we used "VARCHAR" instead of "TEXT" because we didn't need the large text storage and search capabilities of the latter field. Really, we're just storing big strings that get wound up into Java objects.

As a note: JWKS are formatted as JSON encoded values, which are defined as using UTF-8: https://tools.ietf.org/html/rfc7159#section-8.1

**Comment by morungos** [comment]
OK, I'll make up a PR.

There's a subtle hint in: https://hub.docker.com/_/mysql/ (although I am so not a docker person).

> For example, if you want to change the default encoding and collation for all tables to use UTF-8

So it might be that the docker image is using a latin1 encoding by default (normally Swedish IIRC), which uses 1/3 the number of bytes in each row (MySQL is very naive that way) and therefore might just be fine. That would testable using instead:

    $ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

And seeing whether it still works. 

I see where you are with the UTF-8, just was I thinking that since all the values seem to be base64 encoded before JSON, normally, then the UTF-8 will always be latin1 too. But I don't really know the specs, so I'd not be surprised if corners exist.
